### ISSUE TITLE
Teleport does not work

### ISSUE THREAD

**Issue by michael-letcher** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#11]
Hey, I've just started playing but I never seem to teleport with everyone else. I just sit a spawn, while the cut scene plays out, a para-shoot appears on my back and then I die.

I have a ping of 250 as I'm playing from Australia on a US server.

**Comment by fttfbass** [comment]
This typically happens when you join a server too late.  If that's not the case, then I'm sure someone with a little more knowledge will come along and help you out.

**Comment by michael-letcher** [comment]
No it's not that. We would be waiting for the game to start and when it does I see everyone else teleport while I just sit there.

**Comment by jonrainier** [comment]
We will definitely look into this. Our speculation as of right now is that it has to do with your high ping to the server. Thanks for the report.
