### ISSUE TITLE
Random Bombing Zone

### ISSUE THREAD

**Issue by Uelmer** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#12]
Hi, really great Mod. Thank you for your work! But there is a really Game-bashing Problem with the random bombing zone. 

1: There is no chance for you to escape from the Zone because it is not announced, so it just depends on luck if you survive or not. 

2: In the later game - Last 3 Steps of Circle its even more frustrating because you cant run away becaus you have to stay in the circle. So you really worked out and killed you to the final and you got killed by these bombings.

I suggest for the last 2-3 Blue Circle to stop the random bombing. And in general for the bombing: Mark it red and make a delay of 1 minute after the Zone is marked so that you have a chance to escape. That would be really important! Keep on fighting ;-)

**Comment by fttfbass** [comment]
I agree with the above.  A delay would at least give players a chance to get away.  Also, the bombing zones seem to really like to hang around the blue circle towards the end of a game.  It's not uncommon for the bombing zone to engulf the entire blue circle repeatedly.

**Comment by lazyink** [comment]
I have made changes to the bombing scripts that should help with these problems. The red zone should now stop before the final zones. I have also added a 10 second delay to the start of the actual bombing inside the zone which should help with your escape.

**Comment by Uelmer** [comment]
Thank you very much!
