### ISSUE TITLE
Game stuttering

### ISSUE THREAD

**Issue by fttfbass** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#13]
I'm not sure what happened, but all of a sudden the servers are periodically stuttering like we're playing a slideshow.  I thought maybe it was just me, but I hopped onto twitch to watch a stream and he was having the same issues on a different server.  It was an HFB US server that I played on.

**Comment by fttfbass** [comment]
I don't know if it was fixed or an issue with HFB servers, but I played a UK Gaming Deluxe server today and didn't have the same problem.

**Comment by Z0idCrystal** [comment]
+1 Many servers where I get  fps loss. First thinking of lag, then on graphic configuration but same thing in low as on ultra. 60 fps falls to 30 and then go back and so on. I hope this is the anti cheat system working to find and eliminate the fuc**ing cheater I'll post now.

**Comment by fttfbass** [comment]
The performance is still pretty bad at times.  It's not stuttering like a slideshow, but it gets quite laggy.  Maybe I wouldn't notice it as much if I had a better computer, but it was playable a few days ago and now not so much.

**Comment by lazyink** [comment]
How is the performance at the moment? We have made some optimisation changes to the code, which should help with the issues you saw.

**Comment by fttfbass** [comment]
It seems to be a bit better.

**Comment by VeritechHT1** [comment]
Played a nighttime round on a HC server on 21 May 2014 and saw persistent, albeit intermittent stuttering throughout the round. By this I mean that the game would stutter for about a minute then it would go away only to  resume stuttering at a later point. And the stuttering did not happen right away in the match, but later on. I'll look at my video capture to see when it happened (I.e. did it commence after the bombing or after the circle commenced?).

In addition, to echo fttfbass, I was watching a stream last night with a streamer playing on a nighttime HC server and he had the same problem.

Thanks for the help and all the work.

**Comment by Z0idCrystal** [comment]
Yep, still stuttering issues but only on Hardcore. No regular servers where I observed that. You can understand it is really annoying at the end of a round ^^ .

**Comment by lazyink** [comment]
Stuttering is now fixed. For some reason the old fog script was enabled still which was causing these issues.
