### ISSUE TITLE
Airplane falls to the ground 

### ISSUE THREAD

**Issue by duartebenavente** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#17]
This weekend while playing on Uk regular servers, at the begging of the round, the plane just spawns going straight down, crashing and killing everyone instantly.

This happend at least on four different ocasions and on different servers.

**Comment by OZPAX** [comment]
If I were you I would avoid those low-cost basic carriers.  The planes are old, they are noisy and the food is shit.  There are even reports that passengers get tossed out mid-flight, can you believe that?  OK seriously, we are on to that bug and PLAYERUNKNOWN has implemented a fix, hopefully it is the last we see of any more BR air disasters.
