### ISSUE TITLE
No loot in carepackages (New servers)

### ISSUE THREAD

**Issue by thomasboulongne** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#2]
As said in the title, none of the carepackages of the Xtreame servers have loots

**Comment by jonrainier** [comment]
We are currently implementing a system to update all of our servers after every restart. As of this morning the only servers to have this new system implemented are mine and GamingDeluxe. Try to stick with these servers as they are updated as soon as a fix is produced.
