### ISSUE TITLE
Server player recognition.

### ISSUE THREAD

**Issue by DocVoltron** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#3]
A few times yesterday while playing the server would state the amount of players remaining, but it was off by more than a couple. Would also state the winner winner chicken dinner when multiple players were still alive.  Had it happen a couple times yesterday in multiple servers, US East 3, CA 2, UK 1.

**Comment by jonrainier** [comment]
At this point it seems that certain hosts are not fulfilling their duties in properly updating the servers as it is only happening on them. This issue was pushed several days ago and was fixed.

**Comment by fttfbass** [comment]
I played on a Pwnzoz0r server yesterday.  Everything seemed to be working as it should, except that the server restarted abruptly with 2 of us left (the player count was correct and we still had at least one more blue circle).  I would have posted it as a bug, but don't remember which server or what time it occurred.

Currently, every other host still has a pretty broken game at the moment.

**Comment by jonrainier** [comment]
We are in the process of fixing this issue permanently. Expect a fix for it in a day or so.
