### ISSUE TITLE
Player count not exact

### ISSUE THREAD

**Issue by detile** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#6]
Hello,
I've just finished/lost a game in UK#2 server. (wed. 30 April - 10 AM Paris)
Player Count said we were 2. Saw the guy 250 m in front of me. Shooted at him - sooo bad, 2 clips - he was still running and suddenly, i've been shot in the back by ... a ghost.

And yesterday, i saw a streamer been killed many times, and reviving again and again.

**Comment by detile** [comment]
Same problem in UK6 today.

**Comment by jonrainier** [comment]
https://github.com/BattleRoyaleGames/ArmA3-BattleRoyale-Issues/issues/3
