### ISSUE TITLE
Updated servers restarting early with correct player count

### ISSUE THREAD

**Issue by fttfbass** [BattleRoyaleGames/ArmA3-BattleRoyale-Issues#7]
US West 1 Regular (Pwnoz0r) restarted prematurely with 3 players remaining around 13:30 EST.

The player count was correct.  We had at least 3 more blue circles until time would run out.  The same thing happened to me yesterday with 2 players remaining on another Pwnoz0r server.

**Comment by fttfbass** [comment]
It just happened again on another server that is up to date.  I think it was an xtreamline server or something like that (gamingdeluxe seems to be the only host that doesn't have the latest updates).  The player count was correct with 2 of us left.  The radius of the blue circle was about 150m.  I killed the 3rd to last player and about 20-30 seconds later the server kicked us with a restart message.

**Comment by jonrainier** [comment]
https://github.com/BattleRoyaleGames/ArmA3-BattleRoyale-Issues/issues/3
